### PR TITLE
Create COVID-19-World-Data

### PR DESCRIPTION
**Pull request by Praduman30642**
Covid-19 -Silence killer

### CODE REVIEW

**Review by mbiesiad — APPROVED** [review]

**Comment by mbiesiad** [comment]
Hi @Praduman30642 Awesome!! 🔥  Thanks a lot! Best wishes 🚀

**Comment by Praduman30642** [comment]
> Hi @Praduman30642 Awesome!! 🔥 Thanks a lot! Best wishes 🚀

Thanks

**Comment by Praduman30642** [comment]
> Hi @Praduman30642 Awesome!! 🔥 Thanks a lot! Best wishes 🚀

Accept

**Comment by mbiesiad** [comment]
Accepted

**Pull request merged**
